services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://docker:docker@db:5432/api-digital"
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: api-digital
    volumes:
      - db_data:/bitnami/postgresql

volumes:
  db_data:
